// This is the entry-point 
###
GET http://localhost:3001/api/blogs

### To create a new note
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "first blog",
  "author": "tester",
  "url": "www.test.com",
  "likes": 42
}